channels:
    - 'FP01-F07'
    - 'F07-T03'
    - 'T03-T05'
    - 'T05-O01'
    - 'FP02-F08'
    - 'F08-T04'
    - 'T04-T06'
    - 'T06-O02'
    - 'FP01-F03'
    - 'F03-C03'
    - 'C03-P03'
    - 'P03-O01'
    - 'FP02-F04'
    - 'F04-C04'
    - 'C04-P04'
    - 'P04-O02'
    - 'FZ-CZ'